module.exports = [
  {name: 'permission', url: '/permission'},
  {name: 'user', url: '/user'},
  {name: 'paperKind', url: '/papervariety'},
  {name: 'paperCode', url: '/paperCode'},
  {name: 'materialCode', url: '/paperMaterial'},
  {name: 'paperSupplier', url: '/supplier'},
  {name: 'productionLineTrim', url: '/LineWaster'},
  {name: 'customerPackageQuantitySetting', url: '/customerPackageQuantitySetting'},
  {name: 'ruleCustomize', url: '/rule'},
  {name: 'productionLine', url: '/line'},
  {name: 'paperInStock', url: '/paperInStock'},
  {name: 'paperTable', url: '/report'},
  {name: 'warehouse', url: '/warehouse'},
  {name: 'paperWarehouse', url: '/paperWarehouse'},
  {name: 'innerUser', url: '/innerUser'},
  {name: 'branchTask', url: '/divide'},
  {name: 'orderManage', url: '/producePlan'},
  {name: 'orderStatistics', url: '/orderStatistics'},
  {name: 'productionMinority', url: '/few'},
  {name: 'prodTask', url: '/prodTask'},
  {name: 'report', url: '/report'},
  {name: 'plannedMerger', url: '/merge'},
  {name: 'planArrange', url: '/planArrange'},
];
