module.exports = [
  {name: 'permission', url: '/permission'},
  {name: 'user', url: '/user'},
  {name: 'paperKind', url: '/papervariety'},
  {name: 'paperCode', url: '/paperCode'},
  {name: 'materialCode', url: '/paperMaterial'},
  {name: 'paperSupplier', url: '/supplier'},
  {name: 'productionLineTrim', url: '/LineWaster'},
  {name: 'customerPackageQuantitySetting', url: '/customerPackageQuantitySetting'},
  {name: 'ruleCustomize', url: '/rule'},
  {name: 'productionLine', url: '/line'},
  {name: 'paperInStock', url: '/paperInStock'},
  {name: 'paperTable', url: '/report'},
  {name: 'paperWarehouse', url: '/warehouse'},
  {name: 'innerUser', url: '/innerUser'},
];
