//纸筒相关键值对
export default {
  storageTime: 'createTime', //入库时间
  outStockTime: 'createTime', //出库时间
  cylinderNo: 'paperTubeNumber', //纸筒编号
  receiptNumber: 'receiptNumber', //单据编号
  paperSupplierId: 'supplierId', //原纸供应商id
  paperSupplierName: 'supplierName', //原纸供应商名称
  supplierId: 'supplierId', //原纸供应商编号
  storageType: 'storageType', //入库类型
  outStockType: 'storageType', //出库类型
  documentNo: 'receiptNumber', //单据编号
  deliveryBillId: 'deliveryNumber', //送货单号
  deliveryNumber: 'deliveryCarNumber', //送货车号
  totalWeight: 'totalWeight', //总重量
  totalAmount: 'totalNumber', //总件数
  totalMoney: 'totalAmount', //总金额
  remark: 'note', //备注信息
  forkliftDriverId: 'forkliftWorker', //叉车员
  forkliftDriverName: 'forkliftWorkerName', //叉车员姓名
  weight: 'weight', //重量
  length: 'length', //长度
  area: 'area', //面积
  unitPrice: 'unitPrice', //单价
  money: 'amount', //金额
  usePerson: 'recipient', //领用人
  usePersonName: 'recipientName', //领用人名称
  useDepartment: 'receiveDepartment', //领用部门
  useDepartmentName: 'receiveDepartmentName', //领用部门
  useGroup: 'receiveTeam', //领用班组
};
