//订单相关键值对
export default {
  productionNo: 'produceOrderNumber', //生产编号
  orderId: 'grouponOrderNumber', //订单编号
  customerName: 'customerName', //客户名称
  customerId: 'customerId', //客户id
  productName: 'grouponProductName', //产品名称
  materialName: 'grouponProductCode', //材料名称
  fluteType: 'tileModel', //瓦楞楞型
  orderAmount: 'pieceAmount', //订单数量
  materialSize: 'materialSize', //下料规格
  materialLength: 'materialLength', //下料长
  materialWidth: 'materialWidth', //下料宽
  orderStatus: 'orderStatus', //订单状态
  productStatus: 'state', //生产状态
  deliveryTime: 'arriveTime', //订单交期
  layer: 'layers', //层数
  orderType: 'orderType', //订单类型
  contacts: 'contact', //联系人
  contactWay: 'phone', //联系方式
  address: 'address', //地址
  productSize: 'productSize', //产品规格
  linePressingMethod: 'staveType', //压线方式
  longitudinalPressure: 'vformula', //纵压公式
  transversePressure: 'hformula', //横压公式
  materialCode: 'materialCode', //用料代码
  platformMaterialName: 'platformMaterialCode', //平台材料名称
  orderTip: 'grouponOrderFlag', //订单标签
};
