//订单相关键值对
export default {
  productionNo: 'produceOrderNumber', //生产编号
  orderId: 'grouponOrderNumber', //订单编号
  customerName: 'customerName', //客户名称
  customerId: 'customerId', //客户id
  productName: 'grouponProductName', //产品名称
  materialName: 'grouponProductCode', //材料名称
  fluteType: 'tileModel', //瓦楞楞型
  orderAmount: 'pieceAmount', //订单数量
  materialSize: 'materialSize', //下料规格
  materialLength: 'materialLength', //下料长
  materialWidth: 'materialWidth', //下料宽
  orderStatus: 'orderStatus', //订单状态
  productStatus: 'state', //生产状态
  deliveryTime: 'arriveTime', //订单交期
  layer: 'layers', //层数
  orderType: 'orderType', //订单类型
  contacts: 'contact', //联系人
  contactWay: 'phone', //联系方式
  address: 'address', //地址
  productSize: 'productSize', //产品规格
  productLength: 'productLength', //产品规格-长
  productWidth: 'productWidth', //产品规格-宽
  productHeight: 'productHeight', //产品规格-高
  linePressingMethod: 'staveType', //压线方式
  longitudinalPressure: 'vformula', //纵压公式
  transversePressure: 'hformula', //横压公式
  materialCode: 'materialCode', //用料代码
  platformMaterialName: 'platformMaterialCode', //平台材料名称
  orderTip: 'grouponOrderFlag', //订单标签
  packageAmount: 'processeAmount', //打包数量
  consignee: 'consignee', //收货人
  mergeStatus: 'combinedType', //合并状态
  mergeId: 'combineId', //合并状态
  mergeTime: 'createTime', //合并时间
  productAmount: 'produceAmount', //生产数量
  optimalSize: 'calPaperSize', //最优门幅
  cutNumber: 'cut', //切数
  cutterNumber: 'cutterNumber', //刀数
  orderMetres: 'paperLength', //订单米数
  trim: 'wasteWidth', //修边
  trimRate: 'wasterRate', //修边率
  cartonRemarks: 'cartonRemarks', //纸箱备注
  associatedOrders: 'associatedOrders', //关联单号
  stackUp: 'stackUp', //叠单
  sortIndex: 'sortIndex', //订单排序
};
