//订单相关键值对
export default {
  productionNo: 'produceOrderNumber', //生产编号
  orderId: 'grouponOrderNumber', //订单编号
  customerName: 'customerName', //客户名称
  customerId: 'customerId', //客户id
  productName: 'grouponProductName', //产品名称
  materialName: 'grouponProductCode', //材料名称
  fluteType: 'tileModel', //瓦楞楞型
  orderAmount: 'pieceAmount', //订单数量
  materialSize: 'materialSize', //下料规格
  materialLength: 'materialLength', //下料长
  materialWidth: 'materialWidth', //下料宽
  orderStatus: 'orderState', //订单状态
  productStatus: 'state', //生产状态
  deliveryTime: 'arriveTime', //订单交期
  affluxTime: 'affluxTime', //汇入日期
  layer: 'layers', //层数
  orderType: 'orderType', //订单类型
  contacts: 'contact', //收货人
  contactWay: 'phone', //联系方式
  address: 'address', //地址
  productSize: 'productSize', //产品规格
  productLength: 'productLength', //产品规格-长
  productWidth: 'productWidth', //产品规格-宽
  productHeight: 'productHeight', //产品规格-高
  linePressingMethod: 'staveType', //压线方式
  longitudinalPressure: 'vformula', //纵压公式
  transversePressure: 'hformula', //横压公式
  materialCode: 'materialCode', //用料代码
  platformMaterialName: 'platformMaterialCode', //平台材料名称
  orderTip: 'grouponOrderFlag', //订单标签
  packageAmount: 'processeAmount', //打包数量
  consignee: 'consignee', //收货人
  mergeStatus: 'combinedType', //合并状态
  mergeId: 'combineId', //合并状态
  mergeTime: 'createTime', //合并时间
  productAmount: 'produceAmount', //生产数量
  optimalSize: 'calPaperSize', //最优门幅
  cutNumber: 'cut', //切数
  cutterNumber: 'paperCount', //刀数
  orderMetres: 'paperLength', //订单米数
  trim: 'wasteWidth', //修边
  trimRate: 'wasterRate', //修边率
  cartonRemarks: 'remark', //纸箱备注
  associatedOrders: 'associatedOrders', //关联单号
  stackUp: 'isStack', //叠单
  sortIndex: 'sort', //订单排序
  produceMaterial: 'produceMaterial', //生产用料、用料代码
  produceMaterialId: 'produceMaterialId', //生产用料、用料代码Id

  topSheet: 'topSheet', //贴合面纸
  corePaper1: 'corePaper1', //一车芯纸
  facePaper1: 'facePaper1', //一车面纸
  corePaper2: 'corePaper2', //二车芯纸
  facePaper2: 'facePaper2', //二车面纸
  corePaper3: 'corePaper3', //三车芯纸
  facePaper3: 'facePaper3', //三车面纸
  operator: 'operator', //操作人
  branchStatus: 'divideState', //分线状态
  combineId: 'combineId', //合并编号
};
